# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        picture_thumb:
            quality: 100
            filters:
                thumbnail: { size: [120, 120], mode: outbound }
        picture_gallery:
            quality: 100
            filters:
                thumbnail: { size: [800, 800], mode: outbound }
        testimonial_image:
            quality: 100
            filters:
                thumbnail: { size: [120, 120], mode: outbound }
        testimonial_thumb:
            quality: 100
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
